version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=username
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=lacoco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local